// Code generated by protoc-gen-go. DO NOT EDIT.
// source: store.proto

/*
Package store is a generated protocol buffer package.

It is generated from these files:
	store.proto

It has these top-level messages:
	PaxosState
*/
package store

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PaxosState struct {
	InstanceID     uint64 `protobuf:"varint,1,opt,name=InstanceID" json:"InstanceID,omitempty"`
	PromisedBallot uint64 `protobuf:"varint,2,opt,name=PromisedBallot" json:"PromisedBallot,omitempty"`
	AcceptedBallot uint64 `protobuf:"varint,3,opt,name=AcceptedBallot" json:"AcceptedBallot,omitempty"`
	AcceptedValue  []byte `protobuf:"bytes,4,opt,name=AcceptedValue,proto3" json:"AcceptedValue,omitempty"`
}

func (m *PaxosState) Reset()                    { *m = PaxosState{} }
func (m *PaxosState) String() string            { return proto.CompactTextString(m) }
func (*PaxosState) ProtoMessage()               {}
func (*PaxosState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PaxosState) GetInstanceID() uint64 {
	if m != nil {
		return m.InstanceID
	}
	return 0
}

func (m *PaxosState) GetPromisedBallot() uint64 {
	if m != nil {
		return m.PromisedBallot
	}
	return 0
}

func (m *PaxosState) GetAcceptedBallot() uint64 {
	if m != nil {
		return m.AcceptedBallot
	}
	return 0
}

func (m *PaxosState) GetAcceptedValue() []byte {
	if m != nil {
		return m.AcceptedValue
	}
	return nil
}

func init() {
	proto.RegisterType((*PaxosState)(nil), "store.PaxosState")
}

func init() { proto.RegisterFile("store.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 143 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x2e, 0xc9, 0x2f,
	0x4a, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0x16, 0x31, 0x72, 0x71,
	0x05, 0x24, 0x56, 0xe4, 0x17, 0x07, 0x97, 0x24, 0x96, 0xa4, 0x0a, 0xc9, 0x71, 0x71, 0x79, 0xe6,
	0x15, 0x97, 0x24, 0xe6, 0x25, 0xa7, 0x7a, 0xba, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x04, 0x21,
	0x89, 0x08, 0xa9, 0x71, 0xf1, 0x05, 0x14, 0xe5, 0xe7, 0x66, 0x16, 0xa7, 0xa6, 0x38, 0x25, 0xe6,
	0xe4, 0xe4, 0x97, 0x48, 0x30, 0x81, 0xd5, 0xa0, 0x89, 0x82, 0xd4, 0x39, 0x26, 0x27, 0xa7, 0x16,
	0x94, 0xc0, 0xd5, 0x31, 0x43, 0xd4, 0xa1, 0x8a, 0x0a, 0xa9, 0x70, 0xf1, 0xc2, 0x44, 0xc2, 0x12,
	0x73, 0x4a, 0x53, 0x25, 0x58, 0x14, 0x18, 0x35, 0x78, 0x82, 0x50, 0x05, 0x93, 0xd8, 0xc0, 0x4e,
	0x36, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x51, 0x16, 0x6a, 0x35, 0xc1, 0x00, 0x00, 0x00,
}
